#!/usr/bin/env python
'''
Author: Rabin Gaire
for more info visit www.rabingaire.me
follow me at twitter @rabingaire
Happy Coding!!!
'''

import os
import datetime
import time
import json
from gi.repository import Notify, GdkPixbuf

def playbeep():
  os.system('paplay /usr/share/sounds/ubuntu/notifications/Xylo.ogg')

def timenow():
    now = datetime.datetime.now()
    time = ("%s:%s" % (now.hour, now.minute))
    return time

def showNotification(title, body, image):
  notification = Notify.Notification.new(
    title,
    body
  )
  notification.set_icon_from_pixbuf(image)
  notification.set_image_from_pixbuf(image)
  notification.show()
  playbeep()

json_data=open("routine.json").read()
data = json.loads(json_data)

def main():
  now = datetime.datetime.now()
  Notify.init("never kill your time")
  image = GdkPixbuf.Pixbuf.new_from_file("./notification.png")

  while True:
    time.sleep(300)
    for routine in data:
        if routine["time"]==timenow():
            showNotification(routine["title"],routine["body"], image)

    time.sleep(3300)

if __name__ == '__main__':
  main()
